Events.on(ClientLoadEvent, b  => {
UnitTypes.dagger.weapons.get(0).bullet.backColor = Color.valueOf("ffffff");
UnitTypes.fortress.weapons.get(0).bullet.backColor = Color.valueOf("ffffff");
UnitTypes.scepter.weapons.get(0).bullet.backColor = Color.valueOf("ffffff");
UnitTypes.reign.weapons.get(0).bullet.backColor = Color.valueOf("ffffff");
UnitTypes.poly.weapons.get(0).bullet.backColor = Color.valueOf("ffffff");
UnitTypes.mega.weapons.get(0).bullet.backColor = Color.valueOf("ffffff");
UnitTypes.mega.weapons.get(1).bullet.backColor = Color.valueOf("ffffff");
UnitTypes.mega.weapons.get(0).bullet.frontColor = Color.valueOf("ffffff");
UnitTypes.mega.weapons.get(1).bullet.frontColor = Color.valueOf("ffffff");
UnitTypes.quad.weapons.get(0).bullet.backColor = Color.valueOf("ffffff");
UnitTypes.flare.weapons.get(0).bullet.backColor = Color.valueOf("ffffff");
UnitTypes.horizon.weapons.get(0).bullet.backColor = Color.valueOf("ffffff");
UnitTypes.zenith.weapons.get(0).bullet.backColor = Color.valueOf("ffffff");
UnitTypes.antumbra.weapons.get(0).bullet.backColor = Color.valueOf("ffffff");
UnitTypes.antumbra.weapons.get(1).bullet.backColor = Color.valueOf("ffffff");
UnitTypes.antumbra.weapons.get(2).bullet.backColor = Color.valueOf("ffffff");
UnitTypes.eclipse.weapons.get(2).bullet.backColor = Color.valueOf("ffffff");
});
